# Generated by Django 4.0.3 on 2022-07-15 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dibels_test', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queuedimagequestion',
            name='font',
            field=models.ForeignKey(default=268, on_delete=django.db.models.deletion.CASCADE, to='dibels_test.font'),
        ),
        migrations.AlterField(
            model_name='queuedmazequestion',
            name='font',
            field=models.ForeignKey(default=268, on_delete=django.db.models.deletion.CASCADE, to='dibels_test.font'),
        ),
    ]
