# Generated by Django 4.0.3 on 2022-07-21 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dibels_test', '0002_alter_queuedimagequestion_font_and_more'),
        ('dibels_test', '0003_alter_queuedimagequestion_font'),
    ]

    operations = [
    ]
