# Generated by Django 4.0.3 on 2022-07-21 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dibels_test', '0004_merge_20220721_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mazetest',
            name='testAdmin',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
