# Generated by Django 4.0.3 on 2022-07-25 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dibels_test', '0005_alter_mazetest_testadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagetest',
            name='testAdmin',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
